baseURL = "https://www.plane.watch"
languageCode = "en"
theme = ["hugo-video", "blowfish"]
resourceDir = "./resources"

googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
