name: Plane Watch Website - Deploy
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
       
      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: npm
          cache-dependency-path: themes/blowfish/package-lock.json
        
      - name: Install required node modules
        run: |
          cd themes/blowfish
          npm install

      - name: Compile CSS
        run: npm run build
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          
      - name: Build Hugo
        run: hugo --minify
        
      - name: Deploy to WIAB
        # https://github.com/marketplace/actions/ftp-sftp-file-deployer
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: "shell.webinabox.net"
          remote-user: "plane.watch"
          remote-password: ${{ secrets.WIAB_PW_SSH_PW }}
          # only upload the "compiled" static HTML source.
          local-path: "./public/"
          remote-path: "/srv/web/domains/p/plane.watch/public_html"
          sync: full
      
      - name: Status
        id: status
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ job.status }}

      - uses: cl8dep/action-discord@0.1
        name: Discord notification [SUCCESS]
        if: ${{ steps.status.outputs.uppercase == 'SUCCESS'}}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: ✅ Website Deploy (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - uses: cl8dep/action-discord@0.1
        name: Discord notification [FAILURE]
        if: ${{ steps.status.outputs.uppercase == 'FAILURE'}}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: ❌ Website Deploy (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

